version: "2.4"

x-default-options: &default-options
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: isbs-server
    container_name: isbs-server
    init: true
    env_file: server/.env/local.env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      # Delegated option for faster mounted volumes
      - ./server/:/app:delegated
      # Because `yarn install`
      - ./server/package.json:/app/package.json
      - ./server/package-lock.json:/app/package-lock.json
      # Block local modules
      - /app/node_modules
    <<: *default-options

  screen-client:
    build:
      context: ./screen-client
      dockerfile: Dockerfile.dev
    image: isbs-screen-client
    container_name: isbs-screen-client
    init: true
    ports:
      - 3001:3000
    volumes:
      # Delegated option for faster mounted volumes
      - ./screen-client/:/app:delegated
      # Because `yarn install`
      - ./screen-client/package.json:/app/package.json
      - ./screen-client/package-lock.json:/app/package-lock.json
      # Block local modules
      - /app/node_modules
    <<: *default-options

  admin-client:
    build:
      context: ./admin-client
      dockerfile: Dockerfile.dev
    image: isbs-admin-client
    container_name: isbs-admin-client
    init: true
    ports:
      - 3002:3000
    volumes:
      # Delegated option for faster mounted volumes
      - ./admin-client/:/app:delegated
      # Because `yarn install`
      - ./admin-client/package.json:/app/package.json
      - ./admin-client/package-lock.json:/app/package-lock.json
      # Block local modules
      - /app/node_modules
    <<: *default-options
